### ISSUE TITLE
path invalid return by ImagesPicker.openCamera() : "Unable to load asset"

### ISSUE THREAD

**Issue by Vidtion** [flutter-package/images_picker#31]
- iOS端，调用`ImagesPicker.openCamera()` 返回的path不能立即使用，会报"Unable to load asset"，加点延迟就没问题。
- 安卓端没问题

```
images_picker:
    dependency: "direct main"
    description:
      name: images_picker
      url: "https://pub.flutter-io.cn"
    source: hosted
    version: "1.2.4"
```

```
[✓] Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)
```
